# Generated by Django 2.0 on 2018-01-22 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riot_id', models.BigIntegerField()),
                ('time', models.DateTimeField()),
                ('queue_type', models.CharField(max_length=30)),
                ('winner', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('display_name', models.CharField(max_length=30)),
                ('riot_id', models.BigIntegerField()),
                ('region', models.CharField(max_length=5)),
                ('account_id', models.BigIntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='summoner',
            unique_together={('name', 'region')},
        ),
        migrations.AddField(
            model_name='match',
            name='summoner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riot.Summoner'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('riot_id', 'summoner')},
        ),
    ]
