# Generated by Django 2.0 on 2018-02-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
