# Generated by Django 2.0 on 2018-02-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riot', '0002_summoner_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
