# Generated by Django 2.0.2 on 2018-03-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riot', '0003_auto_20180204_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='lane',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='role',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
